import Head from "next/head";
import {motion} from "framer-motion";
import styles from "/styles/Home.module.scss";
import ContactInfoMap from "../components/ContactInfoMap";
import {fadeInUp} from "../animations/animations";
import {getThemesOptionsContent} from "../lib/themesOptions";

// Components
import ContactBanner from "../components/ContactBanner";

const contactUs = ({pageTitle, contactUsPageContent, themesOptionsContent}) => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Contact Us | Kandys Launderette</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logo.png" />
			</Head>

			{/* // <========== BACKGROUND IMAGE ==========> */}
			<div className={styles.backgroundImageContactUs}></div>

			{/* // <========== PAGE TITLE ==========> */}
			<div className={styles.pageTitle}>
				<div>
					<div className={styles.content}>
						<motion.div variants={fadeInUp} className={styles.title}>
							<h2>Contact Us</h2>
							<h5>Lets get In Touch</h5>
						</motion.div>
					</div>
				</div>
			</div>

			{/* <!--===== CONTACT US BANNER =====--> */}
			<ContactInfoMap />
		</motion.div>
	);
};

export default contactUs;
