/* eslint-disable react/no-unknown-property */
import Head from "next/head";
import {gql} from "@apollo/client";
import {client} from "../lib/apollo";
import {motion} from "framer-motion";
import {getThemesOptionsContent} from "../lib/themesOptions";

// Components
import TextImage from "../components/TextImage";
import HeroSection from "../components/HeroSection";
import StoreLocation from "/components/storeLocation";
import ContactBanner from "../components/ContactBanner";
import ContactBannerTwo from "/components/ContactBannerTwo";
import TitleGridContent from "/components/TitleGridContent";
import SpecialOccasions from "../components/SpecialOccasions";
import TitleGridContentTwo from "/components/TitleGridContentTwo";
import TitleParagraphGridContent from "/components/TitleParagraphGridContent";

export default function Home({homePageContent, themesOptionsContent}) {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Kandys Launderette | Professional Dry Cleaning Solutions</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="img/Logo.png" />
			</Head>

			<main>
				{/* <!--===== HERO =====--> */}
				<HeroSection
					title={homePageContent?.heroSection?.title}
					subtitle={homePageContent?.heroSection?.subtitle}
					backgroundImage={
						homePageContent?.heroSection?.backgroundImage?.sourceUrl
					}
				/>

				{/* <!--===== INTRO SECTION =====--> */}
				<TextImage
					title={homePageContent?.textImage?.title}
					subtitle={homePageContent?.textImage?.subtitle}
					paragraph={homePageContent?.textImage?.paragraph}
					buttonLink={homePageContent?.textImage?.buttonLink}
					image={homePageContent?.textImage?.image}
				/>

				{/* <!--===== MAIN SERVICES =====--> */}
				<TitleGridContent
					title={homePageContent?.ourServices?.title}
					paragraph={homePageContent?.ourServices?.paragraph}
					gridContent={homePageContent?.ourServices?.gridContent}
				/>

				{/* <!--===== SPECIAL OCCASIONS =====--> */}
				<SpecialOccasions
					title={homePageContent?.specialOccasions?.title}
					paragraph={homePageContent?.specialOccasions?.paragraph}
					content={homePageContent?.specialOccasions?.content}
				/>

				{/* <!--===== CONTACT US BANNER =====--> */}
				<ContactBanner
					title={homePageContent?.contactBanner?.title}
					paragraph={homePageContent?.contactBanner?.paragraph}
					buttonLink={homePageContent?.contactBanner?.buttonLink}
					backgroundImage={homePageContent?.contactBanner?.image?.sourceUrl}
				/>

				{/* <!--===== WHY CHOOSE US =====--> */}
				<TitleParagraphGridContent
					title={homePageContent?.whyChooseUs?.title}
					paragraph={homePageContent?.whyChooseUs?.paragraph}
					gridContent={homePageContent?.whyChooseUs?.gridContent}
				/>

				{/* <!--===== HOTEL & RESTAURANT =====--> */}
				<TitleGridContentTwo
					title={homePageContent?.hotelRestaurantServices?.title}
					paragraph={homePageContent?.hotelRestaurantServices?.paragraph}
					gridContent={homePageContent?.hotelRestaurantServices?.gridContent}
				/>

				{/* <!--===== INFORMATION SECTION =====--> */}
				<ContactBannerTwo
					title={homePageContent?.contactBannerTwo?.title}
					themesOptions={themesOptionsContent?.themesOptions}
					paragraph={homePageContent?.contactBannerTwo?.paragraph}
					buttonLink={homePageContent?.contactBannerTwo?.buttonLink}
					backgroundImage={homePageContent?.contactBannerTwo?.image?.sourceUrl}
				/>

				{/* <!--===== OUT STORE LOCATION =====--> */}
				<StoreLocation
					title={homePageContent?.ourLocation?.title}
					paragraph={homePageContent?.ourLocation?.paragraph}
				/>
			</main>
		</motion.div>
	);
}

export async function getStaticProps() {
	const getHomePageContent = gql`
		{
			mainContent: pages(where: {id: 168, status: PUBLISH}) {
				edges {
					node {
						homePage {
							heroSection {
								title
								subtitle
								backgroundImage {
									sourceUrl
								}
							}
							textImage {
								title
								subtitle
								paragraph
								displayImageOption
								displayButtonOption
								buttonLink {
									url
									title
									target
								}
								image {
									sourceUrl
									altText
								}
							}
							ourServices {
								title
								paragraph
								gridContent {
									title
									link {
										url
										title
										target
									}
									image {
										sourceUrl
										altText
									}
								}
							}
							specialOccasions {
								title
								paragraph
								content {
									titleTwo
									title
									buttonLinkTwo {
										url
										title
										target
									}
									buttonLink {
										url
										title
										target
									}
									imageTwo {
										sourceUrl
									}
									image {
										sourceUrl
										altText
									}
								}
							}
							contactBanner {
								title
								paragraph
								buttonLink {
									url
									title
									target
								}
								image {
									sourceUrl
								}
							}
							whyChooseUs {
								title
								paragraph
								gridContent {
									title
									paragraph
									image {
										sourceUrl
										altText
									}
								}
							}
							hotelRestaurantServices {
								title
								paragraph
								gridContent {
									title
									link {
										url
										title
										target
									}
									image {
										sourceUrl
										altText
									}
								}
							}
							contactBannerTwo {
								title
								paragraph
								buttonLink {
									url
									title
									target
								}
								image {
									sourceUrl
								}
							}
							ourLocation {
								title
								paragraph
							}
						}
					}
				}
			}
		}
	`;

	const response = await client.query({
		query: getHomePageContent,
	});

	const themesOptionsContent = await getThemesOptionsContent();

	return {
		props: {
			homePageContent: response?.data?.mainContent?.edges[0]?.node?.homePage,
			themesOptionsContent,
		},
		revalidate: 1,
	};
}
