import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

const LaundryDryCleaning = () => {
	return (
		<>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Laundry & Dry Cleaning | Kandys Launderette</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="img/Logo.png" />

				{/* <!-- AOS CDN.js Reveal Animation  --> */}
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
					integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
					crossOrigin="anonymous"
					referrerpolicy="no-referrer"
				/>
				{/* <!-- Bootstrap CSS --> */}
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
					crossOrigin="anonymous"
				/>
				{/* <!-- Bootstrap Icon Link --> */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
				{/* <!-- Icons for Mobile viewport --> */}
				<link
					rel="stylesheet"
					href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
				/>
			</Head>

			{/* <!--===== NAVIGATION =====--> */}
			<Navbar />

			{/* // <========== BACKGROUND IMAGE ==========> */}
			<div className={styles.backgroundImageOne}></div>

			{/* // <========== PAGE TITLE ==========> */}
			<div className={styles.pageTitle}>
				<div className="container">
					<div className={styles.content}>
						<div className={styles.title}>
							<h2>Laundry & Dry Cleaning</h2>
							<h5>From Individual to Business Solutions</h5>
						</div>
					</div>
				</div>
			</div>

			{/* // <========== OPTIONS ==========> */}
			<div className={styles.options}>
				<div className="container">
					<div className={styles.content}>
						<div className={styles.title}>
							<h2>Our Options</h2>
							<h5>
								Choose Between our general self-service option. Or our more
								Tailored Dry Cleaning Service.
							</h5>
						</div>

						<div className={styles.innerContent}>
							<div className={styles.productDisplay}>
								<Link href="LaundryAndDryCleaning/SelfService" target="blank">
									<a>
										<Image
											src="/img/7e9ab8b42c20dc188d175760dd46e191.jpg"
											alt="Product Image"
											width={300}
											height={200}
											layout="responsive"
											objectFit="cover"
										/>
									</a>
								</Link>
								<div className={styles.content}>
									<newButton className={styles.shopButton}>
										<Link
											href="LaundryAndDryCleaning/SelfService"
											target="blank"
										>
											<a>Self-Service</a>
										</Link>
									</newButton>
								</div>
							</div>
							<div className={styles.productDisplay}>
								<Link
									href="LaundryAndDryCleaning/TailoredService"
									target="blank"
								>
									<a>
										<Image
											src="/img/luxury-service.jpg"
											alt="Product Image"
											width={300}
											height={200}
											layout="responsive"
											objectFit="cover"
										/>
									</a>
								</Link>
								<div className={styles.content}>
									<newButton className={styles.shopButton}>
										<Link
											href="LaundryAndDryCleaning/TailoredService"
											target="blank"
										>
											<a>Tailored Service</a>
										</Link>
									</newButton>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</>
	);
};

export default LaundryDryCleaning;
