import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {gql} from "@apollo/client";
import {client} from "../lib/apollo";
import {motion} from "framer-motion";
import styles from "/styles/Home.module.scss";
import {getThemesOptionsContent} from "../lib/themesOptions";
import {fadeInUp, fadeIn, stagger} from "../animations/animations";

// Components
import HeroSection from "../components/HeroSection";
import ContactInfo from "/components/ContactInfo";

const LaundryDryCleaning = ({
	pageTitle,
	laundryDryCleaningPageContent,
	themesOptionsContent,
}) => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>{`Laundry & Dry Cleaning ${pageTitle} | Kandys Launderette`}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="img/Logo.png" />
			</Head>

			<main>
				{/* <!--===== HERO =====--> */}
				<HeroSection
					title={laundryDryCleaningPageContent?.heroSection?.title}
					subtitle={laundryDryCleaningPageContent?.heroSection?.subtitle}
					backgroundImage={
						laundryDryCleaningPageContent?.heroSection?.backgroundImage
							?.sourceUrl
					}
				/>
				{/* // <========== OPTIONS ==========> */}
				<div className={styles.options}>
					<div>
						<div className={styles.content}>
							<motion.div variants={stagger} className={styles.title}>
								<motion.h2 variants={fadeIn}>Our Options</motion.h2>
								<motion.h5 variants={fadeIn}>
									Choose Between our Individual service option. Or our more
									Business tailored dry cleaning service.
								</motion.h5>
							</motion.div>
							<div className={styles.innerContent}>
								<div className={styles.productDisplay}>
									<Link
										href="LaundryAndDryCleaning/IndividualService"
										target="blank"
									>
										<a>
											<Image
												src="/img/Size-Chart-LP_Mens.webp"
												alt="Product Image"
												width={300}
												height={300}
												layout="responsive"
												objectFit="cover"
											/>
										</a>
									</Link>
									<motion.div variants={fadeInUp} className={styles.content}>
										<button className={styles.shopButton}>
											<Link
												href="LaundryAndDryCleaning/IndividualService"
												target="blank"
											>
												<a>Individual Services</a>
											</Link>
										</button>
									</motion.div>
								</div>
								<div className={styles.productDisplay}>
									<Link
										href="LaundryAndDryCleaning/businessService"
										target="blank"
									>
										<a>
											<Image
												src="/img/05a848344f865a82cda0eec6cf53e861.jpg"
												alt="Product Image"
												width={300}
												height={300}
												layout="responsive"
												objectFit="cover"
											/>
										</a>
									</Link>
									<motion.div variants={fadeInUp} className={styles.content}>
										<button className={styles.shopButton}>
											<Link
												href="LaundryAndDryCleaning/businessService"
												target="blank"
											>
												<a>Business Services</a>
											</Link>
										</button>
									</motion.div>
								</div>
							</div>
						</div>
					</div>
				</div>

				{/* <!--===== INFORMATION SECTION =====--> */}
				<ContactInfo />
			</main>
		</motion.div>
	);
};

export default LaundryDryCleaning;

export async function getStaticProps() {
	const getLaundryDryCleaningPageContent = gql`
		{
			mainContent: pages(where: {id: 177, status: PUBLISH}) {
				edges {
					node {
						LaundryDryCleaningPage {
							heroSection {
								title
								subtitle
								backgroundImage {
									sourceUrl
								}
							}
							ourOptions {
								title
								paragraph
								content {
									titleTwo
									title
									image {
										sourceUrl
									}
									imageTwo {
										sourceUrl
									}
									buttonLink {
										url
										title
										target
									}
									buttonLinkTwo {
										url
										title
										target
									}
								}
							}
							contactBanner {
								title
								image {
									sourceUrl
								}
								buttonLink {
									url
									title
									target
								}
							}
						}
					}
				}
			}
		}
	`;

	const response = await client.query({
		query: getLaundryDryCleaningPageContent,
	});

	const themesOptionsContent = await getThemesOptionsContent();

	return {
		props: {
			laundryDryCleaningPageContent:
				response?.data?.mainContent?.edges[0]?.node?.LaundryDryCleaningPage,
			themesOptionsContent,
		},
		revalidate: 1,
	};
}
