import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {motion} from "framer-motion";
import {fadeInUp, fadeIn, stagger} from "../animations/animations";

const services = (pageTitle) => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Laundry & Dry Cleaning | Kandys Launderette</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="img/Logo.png" />
			</Head>
		</motion.div>
	);
};

export default services;
