import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

const WeddingDressesAndBridal = () => {
	return (
		<>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Wedding Dresses & Bridal | Kandys Launderette</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logo.png" />

				{/* <!-- AOS CDN.js Reveal Animation  --> */}
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
					integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
					crossOrigin="anonymous"
					referrerpolicy="no-referrer"
				/>
				{/* <!-- Bootstrap CSS --> */}
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
					crossOrigin="anonymous"
				/>
				{/* <!-- Bootstrap Icon Link --> */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
				{/* <!-- Icons for Mobile viewport --> */}
				<link
					rel="stylesheet"
					href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
				/>
			</Head>

			{/* <!--===== NAVIGATION =====--> */}
			<Navbar />

			{/* // <========== BACKGROUND IMAGE ==========> */}
			<div className={styles.backgroundImageWeddingDressesBridal}></div>

			{/* // <========== PAGE TITLE ==========> */}
			<div className={styles.pageTitle}>
				<div className="container">
					<div className={styles.content}>
						<div className={styles.title}>
							<h2>Wedding Dresses & Bridal</h2>
							<h5>The Best Stress Free Dry Cleaning Solutions.</h5>
						</div>
					</div>
				</div>
			</div>

			{/* // <========== WEDDING DRESS ==========> */}
			<div className={styles.weddingDress}>
				<div className="container">
					<div className={styles.gridDisplay}>
						<div className={styles.Image}>
							<Image
								src="/img/2dadbbf0777ed8a16b24ccde6a6f90dd.jpg"
								alt="Product Image"
								width={400}
								height={800}
								objectFit="cover"
							></Image>
						</div>
						<div className={styles.description}>
							<h2>Wedding Dresses</h2>
							<p>
								We offer wedding dress perpetrations from dry cleaning, Ironing,
								Delivery ready collection. Premium fragrance, sublime sleepwear
								and luxurious accessories.
								<br></br>
								<br></br>
								We want to make your special day stress free, sleep well knowing
								that your wedding dress is taken care of. We want to inspire
								confidence, relaxation and happiness for your special day.
							</p>
						</div>
					</div>
				</div>
			</div>

			{/* // <========== WEDDING DRESS ==========> */}
			<div className={styles.weddingDressProcess}>
				<div className="container">
					<div className={styles.title}>
						<h2>Our Process</h2>
						<h5>From Start to Collection.</h5>
					</div>

					<div className={styles.gridDisplay}>
						<div className={styles.column}>
							<div className={styles.Image}>
								<Image
									src="/img/2dadbbf0777ed8a16b24ccde6a6f90dd.jpg"
									alt="Product Image"
									width={400}
									height={400}
									objectFit="cover"
								></Image>
							</div>
							<div className={styles.description}>
								<h2>Arrival</h2>
								<p>
									Schedule a drop off day. Call us are we can make the best time
									for you to arrive.
									<br></br>
									Be confidence knowing your special dress is in good hands.
									day.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</>
	);
};

export default WeddingDressesAndBridal;
