import Head from "next/head";
import Image from "next/image";
import Navbar from "/components/Navbar";
import OurProcess from "/components/ourProcess";
import ContactInfo from "/components/WeddingDressesAndBridal/ContactInfo";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

const WeddingDressesAndBridal = () => {
	return (
		<>
			{/* <!--===== HEAD =====--> */}
			<Head>
				{/* <!-- Website Title --> */}
				<title>Wedding Dresses & Bridal | Kandys Launderette</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/img/Logo.png" />

				{/* <!-- AOS CDN.js Reveal Animation  --> */}
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
					integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
					crossOrigin="anonymous"
					referrerpolicy="no-referrer"
				/>
				{/* <!-- Bootstrap CSS --> */}
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
					crossOrigin="anonymous"
				/>
				{/* <!-- Bootstrap Icon Link --> */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
				{/* <!-- Icons for Mobile viewport --> */}
				<link
					rel="stylesheet"
					href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
				/>
			</Head>

			{/* <!--===== NAVIGATION =====--> */}
			<Navbar />

			{/* // <========== BACKGROUND IMAGE ==========> */}
			<div className={styles.backgroundImageWeddingDressesBridal}></div>

			{/* // <========== PAGE TITLE ==========> */}
			<div className={styles.pageTitle}>
				<div className="container">
					<div className={styles.content}>
						<div className={styles.title}>
							<h2>Wedding Dresses & Bridesmaid</h2>
							<h5>The Best Stress Free Dry Cleaning Solutions.</h5>
						</div>
					</div>
				</div>
			</div>

			{/* // <========== WEDDING DRESS ==========> */}
			<div className={styles.weddingDress}>
				<div className="container">
					<div className={styles.gridDisplay}>
						<div className={styles.Image}>
							<Image
								src="/img/james-bold-35nWF_04Pgg-unsplash.jpg"
								alt="Product Image"
								width={400}
								height={800}
								objectFit="cover"
							></Image>
						</div>
						<div className={styles.description}>
							<h2>Wedding Dresses</h2>
							<p>
								We offer wedding dress perpetrations from dry cleaning, Ironing,
								Delivery ready collection. Premium fragrance, sublime sleepwear
								and luxurious accessories.
								<br></br>
								<br></br>
								We want to make your special day stress free, sleep well knowing
								that your wedding dress is taken care of. We want to inspire
								confidence, relaxation and happiness for your special day.
							</p>
						</div>
					</div>
				</div>
			</div>

			{/* <!--===== OUR PROCESS INFORMATION =====--> */}
			<OurProcess />

			{/* // <========== WEDDING DRESS PROCESS ==========> */}
			<div className={styles.BridesmaidDress}>
				<div className="container">
					<div className={styles.content}>
						<div className={styles.innerContent}>
							<div className={styles.Image}>
								<Image
									src="/img/katelyn-macmillan-5VhSc5jCA2g-unsplash.jpg"
									alt="Product Image"
									width={800}
									height={800}
									objectFit="contain"
								></Image>
							</div>
							<div className={styles.description}>
								<h2>Bridesmaid Dresses</h2>
								<p>
									We offer Bridesmaid wedding dress perpetrations from dry
									cleaning, Ironing, Delivery ready collection. Premium
									fragrance, sublime sleepwear and luxurious accessories.
									<br></br>
									<br></br>
									We want to make your special day stress free, sleep well
									knowing that your wedding dress is taken care of. We want to
									inspire confidence, relaxation and happiness for your special
									day.
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>

			{/* <!--===== INFORMATION SECTION =====--> */}
			<ContactInfo />

			{/* <!--===== FOOTER =====--> */}
			<Footer />
		</>
	);
};

export default WeddingDressesAndBridal;
