import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {motion} from "framer-motion";
import styles from "/styles/Home.module.scss";
import BusinessServicesListDB from "/lib/IndividualServicesListDB.json";
import ContactBanner from "/components/ContactBanner";

// Custom reusable Animation Properties/variables
const fadeInUp = {
	initial: {
		y: 60,
		opacity: 0,
	},
	animate: {
		y: 0,
		opacity: 1,
		transition: {duration: 0.5, ease: "easeOut"},
	},
};

const fadeIn = {
	initial: {
		opacity: 0,
	},
	animate: {
		opacity: 1,
		transition: {duration: 1, delay: 0.5, ease: "easeOut"},
	},
};

const stagger = {
	animate: {
		transition: {
			staggerChildren: 0.1,
		},
	},
};

const businessService = () => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			<div>
				{/* <!--===== HEAD =====--> */}
				<Head>
					{/* <!-- Website Title --> */}
					<title>Business Tailored Service | Kandys Launderette</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/img/Logo.png" />

					{/* <!-- AOS CDN.js Reveal Animation  --> */}
					<link
						rel="stylesheet"
						href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
						integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
						crossOrigin="anonymous"
						referrerPolicy="no-referrer"
					/>
					{/* <!-- Bootstrap CSS --> */}
					<link
						href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
						rel="stylesheet"
						integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
						crossOrigin="anonymous"
					/>
					{/* <!-- Bootstrap Icon Link --> */}
					<link
						rel="stylesheet"
						href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
					/>
					{/* <!-- Icons for Mobile viewport --> */}
					<link
						rel="stylesheet"
						href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
					/>
				</Head>

				{/* // <========== PAGE TITLE ==========> */}
				<div className={styles.mainContent}>
					<div>
						<div className={styles.previousButton}>
							<Link href="/LaundryDryCleaning">
								<a target="blank">
									<i className="bi bi-arrow-left-circle"></i>
								</a>
							</Link>
						</div>
						<div className={styles.content}>
							<motion.div variants={fadeInUp} className={styles.title}>
								<h2>Business Tailored Service</h2>
								<motion.p variants={fadeIn}>
									Our services provides our business partners professional
									solution to their various requirements. Prior booking is
									required. <br></br>
								</motion.p>
							</motion.div>
							<motion.div variants={fadeIn} className={styles.subtitle}>
								<h2>All Our Services</h2>
							</motion.div>
							<div className={styles.innerContent}>
								<div className={styles.servicesList}>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Duvet Cleaning</h2>
										<ul>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[0].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[1].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[2].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[3].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[4].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[5].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[6].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[7].serviceName}
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Tops & Shirts</h2>
										<ul>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[8].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[9].serviceName}
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Trousers</h2>
										<ul>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[10].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[11].serviceName}
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Bar & Restaurant</h2>
										<ul>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[12].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[13].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[14].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[15].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[16].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[17].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[18].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[19].serviceName}
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Throw-over</h2>
										<ul>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[20].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[21].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[22].serviceName}
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Accessories</h2>
										<ul>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[23].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[24].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[25].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[26].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[27].serviceName}
												</motion.a>
											</Link>
											<Link href="">
												<motion.a variants={fadeInUp} target="blank">
													{BusinessServicesListDB[28].serviceName}
												</motion.a>
											</Link>
										</ul>
									</motion.div>
								</div>
								<div className={styles.servicesDisplays}>
									<div className={styles.ImageBSDivider}></div>
									<motion.div
										variants={stagger}
										className={styles.servicesDisplay}
									>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/supersoft_duvet_1_8.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Duvet Cleaning</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/UK_BuyingGuide_Duvet.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Bed Linen</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/UK_BuyingGuide_Pillows.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Bed Single Blanket</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/Size-Chart-LP_Bed-Linen.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="/">
													<a target="blank">King & Queen Bed</a>
												</Link>
											</div>
										</motion.div>
									</motion.div>
									<div className={styles.ImageBSDividerTwo}></div>
									<motion.div
										variants={stagger}
										className={styles.servicesDisplay}
									>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/491-325s5.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Staff Tops & Shirts</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/skubb-storage-case-dark-grey__0940614_pe795076_s5.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Money Pouch Waist Apron</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/pants-cleaning.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Staff Trousers</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/attention-to-detail.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Waist Coat</a>
												</Link>
											</div>
										</motion.div>
									</motion.div>
									<div className={styles.ImageBSDividerThree}></div>
									<motion.div
										variants={stagger}
										className={styles.servicesDisplay}
									>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/a210e29d04087417d25f542234b19422.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Waiters Uniforms Set</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/26d4c8388751821fbdea71c0c26f46f0.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Kitchen Staff Shirts</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/PH165543-crop001.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Bar Staff Aprons</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="/">
												<a target="blank">
													<Image
														src="/img/Multislider_Barnham_Collection.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="/">
													<a target="blank">Kitchen Cloths</a>
												</Link>
											</div>
										</motion.div>
									</motion.div>
								</div>
							</div>
						</div>
					</div>
				</div>

				{/* <!--===== CONTACT US BANNER =====--> */}
				<ContactBanner />
			</div>
		</motion.div>
	);
};

export default businessService;
