import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

const businessService = () => {
	return (
		<>
			<div>
				{/* <!--===== HEAD =====--> */}
				<Head>
					{/* <!-- Website Title --> */}
					<title>Business Tailored Service | Kandys Launderette</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/img/Logo.png" />

					{/* <!-- AOS CDN.js Reveal Animation  --> */}
					<link
						rel="stylesheet"
						href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
						integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
						crossOrigin="anonymous"
						referrerpolicy="no-referrer"
					/>
					{/* <!-- Bootstrap CSS --> */}
					<link
						href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
						rel="stylesheet"
						integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
						crossOrigin="anonymous"
					/>
					{/* <!-- Bootstrap Icon Link --> */}
					<link
						rel="stylesheet"
						href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
					/>
					{/* <!-- Icons for Mobile viewport --> */}
					<link
						rel="stylesheet"
						href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
					/>
				</Head>

				{/* <!--===== NAVIGATION =====--> */}
				<Navbar />

				{/* // <========== PAGE TITLE ==========> */}
				<div className={styles.mainContent}>
					<div className="container">
						<div className={styles.content}>
							<div className={styles.title}>
								<h2>Business Tailored Service</h2>
								<p>
									Our services provides our business partners professional
									solution to their various requirements. Prior booking is
									required. <br></br>
								</p>
							</div>
							<div className={styles.subtitle}>
								<h2>All Our Services</h2>
							</div>
							<div className={styles.innerContent}>
								<div className={styles.servicesList}>
									<div className={styles.List}>
										<h2>Duvet Cleaning</h2>
										<ul>
											<Link href="">
												<a>Single</a>
											</Link>
											<Link href="">
												<a>Double</a>
											</Link>
											<Link href="">
												<a>Single Blanket</a>
											</Link>
											<Link href="">
												<a>Bed Linen (Single & Double)</a>
											</Link>
											<Link href="">
												<a>Bed Linen (King & Queen)</a>
											</Link>
										</ul>
									</div>
									<div className={styles.List}>
										<h2>Tops & Shirts</h2>
										<ul>
											<Link href="">
												<a>Male Staff Shirts</a>
											</Link>
											<Link href="">
												<a>Female Staff Shirts</a>
											</Link>
											<Link href="">
												<a>Apron Staff Shirts</a>
											</Link>
											<Link href="">
												<a>Women's Waistcoat Staff Shirts</a>
											</Link>
											<Link href="">
												<a>Kitchen Staff Shirts</a>
											</Link>
										</ul>
									</div>
									<div className={styles.List}>
										<h2>Trousers</h2>
										<ul>
											<Link href="">
												<a>Regular Trousers</a>
											</Link>
											<Link href="">
												<a>Silk Trousers</a>
											</Link>
										</ul>
									</div>
									<div className={styles.List}>
										<h2>Skirts</h2>
										<ul>
											<Link href="">
												<a>Regular Skirts</a>
											</Link>
											<Link href="">
												<a>Long Skirts</a>
											</Link>
											<Link href="">
												<a>Part Pleated Skirts</a>
											</Link>
											<Link href="">
												<a>Fully Pleated Skirts</a>
											</Link>
										</ul>
									</div>
									<div className={styles.List}>
										<h2>Dresses</h2>
										<ul>
											<Link href="">
												<a>Day Dress</a>
											</Link>
											<Link href="">
												<a>Silk Day Dress</a>
											</Link>
											<Link href="">
												<a>Plain Evening Dress</a>
											</Link>
											<Link href="">
												<a>Silk Evening Dress</a>
											</Link>
											<Link href="">
												<a>Elaborate Evening Dress</a>
											</Link>
											<Link href="">
												<a>Prom Dress</a>
											</Link>
											<Link href="">
												<a>Ball Grown</a>
											</Link>
										</ul>
									</div>
									<div className={styles.List}>
										<h2>Throw-over</h2>
										<ul>
											<Link href="">
												<a>Single</a>
											</Link>
											<Link href="">
												<a>Double</a>
											</Link>
										</ul>
									</div>
									<div className={styles.List}>
										<h2>Accessories</h2>
										<ul>
											<Link href="">
												<a>Tie</a>
											</Link>
											<Link href="">
												<a>Scarf</a>
											</Link>
											<Link href="">
												<a>Pashmina</a>
											</Link>
											<Link href="">
												<a>Wrap</a>
											</Link>
											<Link href="">
												<a>Hats</a>
											</Link>
											<Link href="">
												<a>Dressing Gown</a>
											</Link>
											<Link href="">
												<a>Waist Coat</a>
											</Link>
											<Link href="">
												<a>Silk Waist Coat</a>
											</Link>
										</ul>
									</div>
								</div>
								<div className={styles.servicesDisplays}>
									<div className={styles.ImageBSDivider}></div>
									<div className={styles.servicesDisplay}>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/04438fc4fc1a9a09b7c2e06de39eccee.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Laundry & Dry Cleaning</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/491-325s2.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Grooms Suit Cleaning & Alterations</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/2dadbbf0777ed8a16b24ccde6a6f90dd.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Bridal Dress Cleaning & Alterations</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/231-419s.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Alterations & Repairs</a>
												</Link>
											</div>
										</div>
									</div>
									<div className={styles.ImageBSDividerTwo}></div>
									<div className={styles.servicesDisplay}>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/572e21864592e57f4a6d121be547b12d.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Professional Ironing Services</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/f46c1141fb97af8cc03149945a4f19c4.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Self-Services</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/supersoft_duvet_2_2_2.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Duvet & Quilts Cleaning</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/cashmere-care-step2.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Stain Removing</a>
												</Link>
											</div>
										</div>
									</div>
									<div className={styles.ImageBSDividerThree}></div>
									<div className={styles.servicesDisplay}>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/209-116s4.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Oxford Shirts</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/Invest_in_Downtime_Image_1.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Restaurant Laundry & Linen Cleaning</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/221-057s.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Jacket & Coat Alterations</a>
												</Link>
											</div>
										</div>
										<div className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/stuk-organiser-white__1035115_pe837986_s5.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Kids Clothing Alterations</a>
												</Link>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				{/* <!--===== FOOTER =====--> */}
				<Footer />
			</div>
		</>
	);
};

export default businessService;
