import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

const IndividualService = () => {
	return (
		<>
			<div>
				{/* <!--===== HEAD =====--> */}
				<Head>
					{/* <!-- Website Title --> */}
					<title>Self-Service | Kandys Launderette</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="img/Logo.png" />

					{/* <!-- AOS CDN.js Reveal Animation  --> */}
					<link
						rel="stylesheet"
						href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
						integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
						crossOrigin="anonymous"
						referrerpolicy="no-referrer"
					/>
					{/* <!-- Bootstrap CSS --> */}
					<link
						href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
						rel="stylesheet"
						integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
						crossOrigin="anonymous"
					/>
					{/* <!-- Bootstrap Icon Link --> */}
					<link
						rel="stylesheet"
						href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
					/>
					{/* <!-- Icons for Mobile viewport --> */}
					<link
						rel="stylesheet"
						href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
					/>
				</Head>

				{/* <!--===== NAVIGATION =====--> */}
				<Navbar />

				{/* // <========== PAGE TITLE ==========> */}
				<div className={styles.mainContent}>
					<div className="container">
						<div className={styles.content}>
							<div className={styles.title}>
								<h2>Individual Self-Service</h2>
								<p>
									Our Individual Self-Services allows any of our customers to
									arrive at our store are select the various options we provide.
									No prior booking required. <br></br>
									Most our customer book in advance when they need their items
									completed by and when they plan to arrive.
								</p>
							</div>
							<div className={styles.subtitle}>
								<h2>All Services</h2>
							</div>
							<div className={styles.servicesDisplay}>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/8b0c89140159be4416593876eeefd470.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Laundry & Dry Cleaning</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/7e2461b51ed38f933ff6794e44025826.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Grooms Suit Cleaning & Alterations</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/8ee51b5c1c83023731f8c9ca972a9c3e.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Bridal Dress Cleaning & Alterations</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/trousers-alterations.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Alterations & Repairs</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/22679eb6cd65c24b2d14f7910980ec95.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Professional Ironing Services</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/f46c1141fb97af8cc03149945a4f19c4.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Self-Services</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/supersoft_duvet_1_8.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Duvet & Quilts Cleaning</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/cashmere-care-step3.webp"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Stain Removing</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/209-116s2.webp"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Oxford Shirts</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/ORGANICFC02_15_T.webp"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Restaurant Laundry & Linen Cleaning</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/920015s12.webp"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>

									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Jacket & Coat Alterations</a>
										</Link>
									</div>
								</div>
								<div className={styles.content}>
									<Link href="#launderette" target="blank">
										<a>
											<Image
												src="/img/pexels-sarah-chai-7282372.jpg"
												alt="Product Image"
												width={400}
												height={400}
												objectFit="cover"
											></Image>
										</a>
									</Link>
									<div className={styles.header}>
										<Link href="#launderette" target="blank">
											<a>Kids Clothing Alterations</a>
										</Link>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

				{/* <!--===== FOOTER =====--> */}
				<Footer />
			</div>
		</>
	);
};

export default IndividualService;
