import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import {motion} from "framer-motion";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

// Custom reusable Animation Properties/variables
const fadeInUp = {
	initial: {
		y: 60,
		opacity: 0,
	},
	animate: {
		y: 0,
		opacity: 1,
		transition: {duration: 0.5, ease: "easeOut"},
	},
};

const fadeIn = {
	initial: {
		opacity: 0,
	},
	animate: {
		opacity: 1,
		transition: {duration: 1, delay: 0.5, ease: "easeOut"},
	},
};

const stagger = {
	animate: {
		transition: {
			staggerChildren: 0.1,
		},
	},
};

const IndividualService = () => {
	return (
		<motion.div
			exit={{
				opacity: 0,
			}}
			initial="initial"
			animate="animate"
		>
			<div>
				{/* <!--===== HEAD =====--> */}
				<Head>
					{/* <!-- Website Title --> */}
					<title>Individual Self-Service | Kandys Launderette</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/img/Logo.png" />

					{/* <!-- AOS CDN.js Reveal Animation  --> */}
					<link
						rel="stylesheet"
						href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
						integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
						crossOrigin="anonymous"
						referrerpolicy="no-referrer"
					/>
					{/* <!-- Bootstrap CSS --> */}
					<link
						href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
						rel="stylesheet"
						integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
						crossOrigin="anonymous"
					/>
					{/* <!-- Bootstrap Icon Link --> */}
					<link
						rel="stylesheet"
						href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
					/>
					{/* <!-- Icons for Mobile viewport --> */}
					<link
						rel="stylesheet"
						href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
					/>
				</Head>

				{/* <!--===== NAVIGATION =====--> */}
				<Navbar />

				{/* // <========== PAGE TITLE ==========> */}
				<div className={styles.mainContent}>
					<div className="container">
						<div className={styles.previousButton}>
							<Link href="/LaundryDryCleaning">
								<a>
									<i className="bi bi-arrow-left-circle"></i>
								</a>
							</Link>
						</div>
						<div className={styles.content}>
							<motion.div variants={fadeInUp} className={styles.title}>
								<h2>Individual Self-Service</h2>
								<motion.p variants={fadeIn}>
									Our Individual Self-Services allows any of our customers to
									arrive at our store are select the various options we provide.
									No prior booking required. <br></br>
									Most our customer book in advance when they need their items
									completed by and when they plan to arrive.
								</motion.p>
							</motion.div>
							<motion.div variants={fadeIn} className={styles.subtitle}>
								<h2>All Our Services</h2>
							</motion.div>
							<div className={styles.innerContent}>
								<div className={styles.servicesList}>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Suits</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>2 Piece Suit</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													2 Piece Dress Suit
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													2 Piece Dinner Suit
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>3 Piece Suit</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Trousers</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Regular Trousers
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Silk Trousers</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Skirts</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Regular Skirts</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Long Skirts</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Part Pleated Skirts
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Fully Pleated Skirts
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Dresses</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Day Dress</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Silk Day Dress</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Plain Evening Dress
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Silk Evening Dress
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Elaborate Evening Dress
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Prom Dress</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Ball Grown</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Coats</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													3/4 Length Wool Coat
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Full Length Coat
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Raincoat / Mack</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Puffa Jacket</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Fake Fur Fabrics
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Tops & Shirts</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Shirts</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Lightweight Jumper
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Evening Top</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Bustier Top</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Silk Bustier Top
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Silk Shirt </motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Jackets</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Jackets</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Throw-over</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Single</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Double</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Wedding Items</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Wedding Dress</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Boxed</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Silk Wedding Dress
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Bridesmaids Dresses
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Flower Girl Dress
												</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Accessories</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Tie</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Scarf</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Pashmina</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Wrap</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Hats</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Dressing Gown</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Waist Coat</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Silk Waist Coat</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Duvet Cleaning</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Single</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Double</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Single Blanket</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Sleeping Bag</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>Single</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Double</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>Child Size</motion.a>
											</Link>
										</ul>
									</motion.div>
									<motion.div variants={stagger} className={styles.List}>
										<h2>Full Bags</h2>
										<ul>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													Large - Wash, Dry & Fold
												</motion.a>
											</Link>
											<Link href="/">
												<motion.a variants={fadeInUp}>
													XL - Wash, Dry & Fold
												</motion.a>
											</Link>
										</ul>
									</motion.div>
								</div>
								<div className={styles.servicesDisplays}>
									<div className={styles.ImageDivider}></div>
									<motion.div
										variants={stagger}
										className={styles.servicesDisplay}
									>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/04438fc4fc1a9a09b7c2e06de39eccee.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Laundry & Dry Cleaning</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/benjamin-rascoe-WdhmRPvMn7A-unsplash.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Grooms Suit Cleaning & Alterations</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/2dadbbf0777ed8a16b24ccde6a6f90dd.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Bridal Dress Cleaning & Alterations</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/231-419s.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Alterations & Repairs</a>
												</Link>
											</div>
										</motion.div>
									</motion.div>
									<div className={styles.ImageDividerTwo}></div>
									<motion.div
										variants={stagger}
										className={styles.servicesDisplay}
									>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/572e21864592e57f4a6d121be547b12d.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Professional Ironing Services</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/f46c1141fb97af8cc03149945a4f19c4.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Self-Services</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/supersoft_duvet_2_2_2.jpg"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Duvet & Quilts Cleaning</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/cashmere-care-step2.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Stain Removing</a>
												</Link>
											</div>
										</motion.div>
									</motion.div>
									<div className={styles.ImageDividerThree}></div>
									<motion.div
										variants={stagger}
										className={styles.servicesDisplay}
									>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/209-116s4.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Oxford Shirts</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/Multislider_Rustic_Linen_Napkins.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Restaurant Laundry & Linen Cleaning</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/221-057s.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>

											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Jacket & Coat Alterations</a>
												</Link>
											</div>
										</motion.div>
										<motion.div variants={fadeInUp} className={styles.content}>
											<Link href="#launderette" target="blank">
												<a>
													<Image
														src="/img/stuk-organiser-white__1035115_pe837986_s5.webp"
														alt="Product Image"
														width={400}
														height={400}
														objectFit="cover"
													></Image>
												</a>
											</Link>
											<div className={styles.header}>
												<Link href="#launderette" target="blank">
													<a>Kids Clothing Alterations</a>
												</Link>
											</div>
										</motion.div>
									</motion.div>
								</div>
							</div>
						</div>
					</div>
				</div>

				{/* <!--===== FOOTER =====--> */}
				<Footer />
			</div>
		</motion.div>
	);
};

export default IndividualService;
