import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "/components/Navbar";
import Footer from "/components/Footer";
import styles from "/styles/Home.module.scss";

const SelfService = () => {
	return (
		<>
			<div>
				{/* <!--===== HEAD =====--> */}
				<Head>
					{/* <!-- Website Title --> */}
					<title>Self-Service | Kandys Launderette</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="img/Logo.png" />

					{/* <!-- AOS CDN.js Reveal Animation  --> */}
					<link
						rel="stylesheet"
						href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
						integrity="sha512-1cK78a1o+ht2JcaW6g8OXYwqpev9+6GqOkz9xmBN9iUUhIndKtxwILGWYOSibOKjLsEdjyjZvYDq/cZwNeak0w=="
						crossOrigin="anonymous"
						referrerpolicy="no-referrer"
					/>
					{/* <!-- Bootstrap CSS --> */}
					<link
						href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
						rel="stylesheet"
						integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
						crossOrigin="anonymous"
					/>
					{/* <!-- Bootstrap Icon Link --> */}
					<link
						rel="stylesheet"
						href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
					/>
					{/* <!-- Icons for Mobile viewport --> */}
					<link
						rel="stylesheet"
						href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"
					/>
				</Head>

				{/* <!--===== NAVIGATION =====--> */}
				<Navbar />

				{/* // <========== PAGE TITLE ==========> */}
				<div className={styles.mainContent}>
					<div className="container">
						<div className={styles.content}>
							<div className={styles.title}>
								<h2>Individual Self-Service</h2>
								<p>
									Our Individual Self-Services allows any of our customers to
									arrive at our store are select the various options we provide.
									No prior booking required. <br></br>
									Most our customer book in advance when they need their items
									completed by and when they plan to arrive.
								</p>
							</div>
						</div>
					</div>
				</div>

				{/* <!--===== FOOTER =====--> */}
				<Footer />
			</div>
		</>
	);
};

export default SelfService;
